### ISSUE TITLE
Steam group servers list

### ISSUE THREAD

**Issue by accelerator74** [Tsuey/L4D2-Community-Update#379] opened 2023-06-22 06:06 UTC
### Description

I think everyone knows that many servers cling to steam groups, in particular, Chinese servers abuse this. This wouldn't be a big problem if the sorting of the given list was correct. But for many in the world, Chinese servers and in principle servers with higher ping load faster, which breaks the search results and does not provide the best server for the player in terms of ping.
![1](https://github.com/Tsuey/L4D2-Community-Update/assets/18032476/2f1dbce2-2277-4de6-b39e-be0f74e063d0)
![2](https://github.com/Tsuey/L4D2-Community-Update/assets/18032476/573a77ab-e7f2-4d29-9c4d-f57015719280)
![3](https://github.com/Tsuey/L4D2-Community-Update/assets/18032476/bba64b16-11b8-49f2-bfcf-4a9073889b5f)
However, the best servers for a player are loaded after a very long time and when the Steam group server list is already broken because it loaded over 1000 servers and in the end, we see this:
![bug](https://github.com/Tsuey/L4D2-Community-Update/assets/18032476/d6792ef1-6a03-43fc-8fe4-f827c3a882aa)
I hope something can be done about this...

**Comment by accelerator74** [comment] 2023-06-22 06:07
Oh, double... Sorry

**Comment by accelerator74** [comment] 2023-06-22 06:17
Here i bring up the problem that steam group servers are not offering the player the best server according to ping.

**Comment by alexiscoutinho** [comment] 2023-06-22 15:11
Partial duplicate of #147, as implied.

**Comment by accelerator74** [comment] 2024-01-19 14:36
I'll leave it in case it gets fixed someday.

When starting the game Left 4 Dead 2, the client accesses the master server and receives a list of servers that are linked to the groups in which the player is a member (`CServerManager::FetchGroupServers`). The list for further polling of servers is formed based on ping, in the `CServerManager::ServerResponded` function of the matchmaking library, in `m_ServersPinging`. After processing all the received servers, the game starts making a group request to each server in `CServerManager::RequestPingingDetails`. If there are few servers tied to any group, then there will be no problems, the game will have time to poll all the servers. But if there are a lot of them, then problems arise in the interface and code. Because of this, the servers are incorrectly sorted in the client's list, and only a few servers that were polled first (their number is about 40-50) will be comfortable for the player, based on ping.

As I believe, this is due to a breakdown in the order in the list of servers in `m_ServersPinging`. After receiving a response from the server, the client deletes the polled server from `m_ServersPinging`, but when deleting, the order of the items in this list is violated, because the delete function `FindAndFastRemove` and `FastRemove` are used, which, judging by the documentation, do not preserve the order when deleted. To preserve the order of this list, it would be better to use `FindAndRemove` in `CServerManager::OnEvent` and `Remove` in `CServerManager::RequestPingingDetails`. Logically, in this case, the servers will be displayed in the game according to their ping, as well as polled in the correct order.

Also, to avoid errors in the game interface, it is worth limiting the client section of the Steam Group Servers to 999 servers. 1000 or more servers will cause the list to overflow and the interface to malfunction. I think this can also be done in the `CServerManager function::RequestPingingDetails` by limiting the polling cycle.

**Comment by accelerator74** [comment] 2024-01-26 12:58
The result of the correction, by patching the library matchmaking.dll
![161105046 74_image](https://github.com/Tsuey/L4D2-Community-Update/assets/18032476/7517b2ac-2eb7-4f62-a861-1ac917c2dbbe)
![161118506 97500002_image](https://github.com/Tsuey/L4D2-Community-Update/assets/18032476/a6110c5a-b79e-4b01-9e0d-9690e096bed6)
![161128782 71000007_image](https://github.com/Tsuey/L4D2-Community-Update/assets/18032476/e648ad02-fe13-4f2f-88e2-297c83d3dee6)

**Closed** 2024-03-26 19:05 UTC
Labels: bug
