### ISSUE TITLE
Tank appears after survivors leave safe house or just after elevator opens on c1m4_atrium

### ISSUE THREAD

**Issue by Pentaphon** [Tsuey/L4D2-Community-Update#101] opened 2021-10-09 10:46 UTC
https://www.reddit.com/r/l4d2/comments/q48qh0/ive_never_seen_the_finale_start_just_as_the/

Video of the Tank appearing when the elevator opens. No video of the Tank appearing after the survivors leave the safe house but the comments confirm it happens sometimes.

**Comment by Pentaphon** [comment] 2021-10-09 11:43
> Can you confirm if this was this on an official server?

I can confirm what happens in the video happens on official servers but I can't confirm if spawning before the elevator happens on official servers since the only time I can definitely remember a tank spawn before the elevator was on a custom server. I am mostly going on personal experience and I was reminded by that reddit post and decided to submit it as evidence that the tanks spawn before that finale.

**Comment by Tsuey** [comment] 2021-10-09 11:51
Appreciate the report and I saw that thread earlier, though I'd suspect this is a duplicate of https://github.com/Tsuey/L4D2-Community-Update/issues/48

Exact cause is unknown but it can be reproduced exactly as such if you empty the _finale.nut files.

**Comment by Tsuey** [comment] 2022-04-14 22:47
This specific manifestation of the VScript failure bug was investigated for several hours yesterday, and fixed today:

https://steamcommunity.com/games/L4D2/announcements/detail/3212764157770533074

More info [is in this thread](https://steamcommunity.com/app/550/discussions/0/1639788130274252869) and, while it's possible VScript anomalies may persist, today's update fixed the most infamous cause, and Dead Center 4 and RocketDude were guinea pigs.

**Closed by Tsuey** 2022-04-14 22:47 UTC
Labels: question

**Comment by Tsuey** [comment] 2022-04-25 23:51
Quick note that this VScript failure bug fix reduces my concerns over PR #131 -- the Commentary clips are **dramatically safer if not completely safe** as converted to VScript.
